host: 127.0.0.1
port: 25565
protocol: 754

proxies: proxies.txt
connections: 150
slow_cooldown: 5000 # milliseconds
fast_cooldown: 250 # ms, this cooldown is used when proxy responds with error
timeout: 5 # seconds

chat_spam: false
chat_cooldown: 3000 # milliseconds
do_activity: false # swing arm + jump + head rotations
hit_respond: false

packet_spam: false
packet_cooldown: 25 # milliseconds

register: true
register_command: /register randomae124
login_command: /login randomae124

phrases:
  - Hello!
  - Hi!
  - o_O
